export const PROFILE_OWNED_RESPONSE_LIMIT = 10;
export const PROFILE_ONSALE_RESPONSE_LIMIT = 10;
export const PROFILE_COLLECTION_RESPONSE_LIMIT = 10;
export const COLLECTION_MINTED_RESPONSE_LIMIT = 10;
export const COLLECTION_ACTIVITY_RESPONSE_LIMIT = 10;
export const NFT_ACTIVITY_RESPONSE_LIMIT = 10;
export const FEED_RESPONSE_LIMIT = 10;
export const STAKER_RESPONSE_LIMIT = 10;
