const REDEEMABLE_NFT_CHAIN_PREFIX = 'redeemableNftChain';
const COLLECTION_CHAIN_PREFIX = 'collectionChain';
const UNAVAILABLE_COLLECTION_CHAIN_PREFIX = 'unavailableCollectionChain';
const NFT_TEMPLATE_CHAIN_PREFIX = 'nftTemplateChain';
const NFT_TEMPLATE_GENESIS_PREFIX = 'nftTemplateGenesis';
const MOMENT_CHAIN_PREFIX = 'momentChain';

export const CHAIN_STATE_ALL_NFT = `${REDEEMABLE_NFT_CHAIN_PREFIX}:all`;
export const CHAIN_STATE_NFT = REDEEMABLE_NFT_CHAIN_PREFIX;
export const CHAIN_STATE_ALL_COLLECTION = `${COLLECTION_CHAIN_PREFIX}:all`;
export const CHAIN_STATE_ALL_UNAVAILABLE_COLLECTION = `${UNAVAILABLE_COLLECTION_CHAIN_PREFIX}:all`;
export const CHAIN_STATE_COLLECTION = COLLECTION_CHAIN_PREFIX;
export const GENESIS_STATE_ALL_NFT_TEMPLATE = `${NFT_TEMPLATE_GENESIS_PREFIX}:all`;
export const CHAIN_STATE_ALL_NFT_TEMPLATE = `${NFT_TEMPLATE_CHAIN_PREFIX}:all`;
export const CHAIN_STATE_NFT_TEMPLATE = NFT_TEMPLATE_CHAIN_PREFIX;
export const CHAIN_STATE_MOMENT = `${MOMENT_CHAIN_PREFIX}`;
export const CHAIN_STATE_ALL_MOMENT = `${MOMENT_CHAIN_PREFIX}:all`;
