export const VALIDATION = {
  MINSTAKE: '1000',
  IPFS_CID_v1_MAXLENGTH: 59,
  ID_MAXLENGTH: 64,
  MIME_MAXLENGTH: 255,
  FILE_EXTENSION_MAXLENGTH: 32,
  FILE_PROTOCOL_MAXLENGTH: 16,
  PUBLIC_KEY_MAXLENGTH: 64,
  SIGNATURE_MAXLENGTH: 128,
};
