const REDEEMABLE_NFT_MODULE_ID = 1000;
const REDEEMABLE_NFT_CREATE_ONEKIND_NFT = 1;
const REDEEMABLE_NFT_MINT_NFT = 4;

module.exports = {
  REDEEMABLE_NFT_MODULE_ID,
  REDEEMABLE_NFT_CREATE_ONEKIND_NFT,
  REDEEMABLE_NFT_MINT_NFT,
};
