const REDEEMABLE_NFT_MODULE_ID = 1000;
const REDEEMABLE_NFT_CREATE_ONEKIND_NFT = 1;
const REDEEMABLE_NFT_MINT_NFT = 4;
const REDEEMABLE_NFT_REQUEST_REDEEM = 5;
const REDEEMABLE_NFT_DELIVER_REDEEM = 6;
const REDEEMBALE_NFT_REJECT_REDEEM = 7;

module.exports = {
  REDEEMABLE_NFT_MODULE_ID,
  REDEEMABLE_NFT_CREATE_ONEKIND_NFT,
  REDEEMABLE_NFT_MINT_NFT,
  REDEEMABLE_NFT_REQUEST_REDEEM,
  REDEEMABLE_NFT_DELIVER_REDEEM,
  REDEEMBALE_NFT_REJECT_REDEEM,
};
