import like from './like';

export const {
  accessCollectionLikeById,
  accessCommentClubsLikeById,
  accessCommentLikeById,
  accessLiked,
  accessNFTLikeById,
  accessReplyClubsLikeById,
  accessReplyLikeById,
  addCollectionLikeById,
  addCommentClubsLikeById,
  addCommentLikeById,
  addNFTLikeById,
  addReplyClubsLikeById,
  addReplyLikeById,
  getCollectionLikeById,
  getCommentClubsLikeById,
  getCommentLikeById,
  getLiked,
  getNFTLikeById,
  getReplyClubsLikeById,
  getReplyLikeById,
  setCollectionLikeById,
  setCommentClubsLikeById,
  setCommentLikeById,
  setLiked,
  setNFTLikeById,
  setReplyClubsLikeById,
  setReplyLikeById,
} = like;
